plugins {
    id 'java'
    id 'jacoco'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

jacocoTestReport {
    reports {
        xml.required = true
    }
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                    'ru/nsu/ziabkin/app/Main.class',
                    'ru/nsu/ziabkin/app/SnakeGameApp.class',
                    'ru/nsu/ziabkin/controllers/GameController.class',
                    'ru/nsu/ziabkin/models/GameModel.class',
                    'ru/nsu/ziabkin/views/GameView.class'
            ])
        }))
    }
}

javafx {
    version = "17"
    modules = [ 'javafx.controls', 'javafx.fxml', 'javafx.media' ]
}

application {
    mainClass = 'app.Main'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}